#!/bin/bash

# Git branches

PAR=$1
BRANCH=$2

if [ ! -z $PAR ]; then
    if [[ "$PAR" == "-d" || "$PAR" == "-rd" || "$PAR" == "-dd" ]]; then
        if [ -z $BRANCH ]; then
            echo "You must enter a branch to delete."
        else
            if [ "$PAR" == "-dd" ]; then
                git branch -d "$BRANCH"
                git push origin --delete "$BRANCH"
                echo "Deleted local and remote branch $BRANCH"
            elif [ "$PAR" == "-rd" ]; then
                git push origin --delete "$BRANCH"
                echo "Deleted remote branch $BRANCH"
            else
                git branch -d "$BRANCH"
                echo "Deleted local branch $BRANCH"
            fi
        fi
    else
        git branch "$PAR"
    fi
else
    git branch
fi
